quarkus.http.port=8092


# --- DB (Fixed hyphen in URL) ---
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/record_db
quarkus.hibernate-orm.schema-management.strategy=update

# --- KAFKA (Ensured both property types) ---
kafka.bootstrap.servers=127.0.0.1:9092
quarkus.devservices.enabled=false

# --- MESSAGING ---
mp.messaging.incoming.proposal-channel.connector=smallrye-kafka
mp.messaging.incoming.proposal-channel.topic=proposal

mp.messaging.incoming.quotation-channel.connector=smallrye-kafka
mp.messaging.incoming.quotation-channel.topic=quotation

#test for sonar